name: deploy website

on:
    push:
        tags:
            - "v*"
        paths:
            - site/**

jobs:
    prod:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: site
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.2
            - run: pnpm i --frozen-lockfile
            - run: pnpm build
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: site/dist
                  cname: gender-predictor.nguyenrk.com
